// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv.proto

#ifndef PROTOBUF_kv_2eproto__INCLUDED
#define PROTOBUF_kv_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace ss7config {
class ConfigGroup;
class ConfigGroupDefaultTypeInternal;
extern ConfigGroupDefaultTypeInternal _ConfigGroup_default_instance_;
class ConfigGroup_ConfigItemsEntry;
class ConfigGroup_ConfigItemsEntryDefaultTypeInternal;
extern ConfigGroup_ConfigItemsEntryDefaultTypeInternal _ConfigGroup_ConfigItemsEntry_default_instance_;
class ConfigItem;
class ConfigItemDefaultTypeInternal;
extern ConfigItemDefaultTypeInternal _ConfigItem_default_instance_;
class ConfigItem_ChildrenFieldsEntry;
class ConfigItem_ChildrenFieldsEntryDefaultTypeInternal;
extern ConfigItem_ChildrenFieldsEntryDefaultTypeInternal _ConfigItem_ChildrenFieldsEntry_default_instance_;
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class Event;
class EventDefaultTypeInternal;
extern EventDefaultTypeInternal _Event_default_instance_;
class KVs;
class KVsDefaultTypeInternal;
extern KVsDefaultTypeInternal _KVs_default_instance_;
class KVs_KvEntry;
class KVs_KvEntryDefaultTypeInternal;
extern KVs_KvEntryDefaultTypeInternal _KVs_KvEntry_default_instance_;
class ss7Config;
class ss7ConfigDefaultTypeInternal;
extern ss7ConfigDefaultTypeInternal _ss7Config_default_instance_;
class ss7Config_Ss7ConfigEntry;
class ss7Config_Ss7ConfigEntryDefaultTypeInternal;
extern ss7Config_Ss7ConfigEntryDefaultTypeInternal _ss7Config_Ss7ConfigEntry_default_instance_;
}  // namespace ss7config

namespace ss7config {

namespace protobuf_kv_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_kv_2eproto

enum ConfigItem_change_type {
  ConfigItem_change_type_NEW = 0,
  ConfigItem_change_type_MODIFIED = 1,
  ConfigItem_change_type_ConfigItem_change_type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ConfigItem_change_type_ConfigItem_change_type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ConfigItem_change_type_IsValid(int value);
const ConfigItem_change_type ConfigItem_change_type_change_type_MIN = ConfigItem_change_type_NEW;
const ConfigItem_change_type ConfigItem_change_type_change_type_MAX = ConfigItem_change_type_MODIFIED;
const int ConfigItem_change_type_change_type_ARRAYSIZE = ConfigItem_change_type_change_type_MAX + 1;

const ::google::protobuf::EnumDescriptor* ConfigItem_change_type_descriptor();
inline const ::std::string& ConfigItem_change_type_Name(ConfigItem_change_type value) {
  return ::google::protobuf::internal::NameOfEnum(
    ConfigItem_change_type_descriptor(), value);
}
inline bool ConfigItem_change_type_Parse(
    const ::std::string& name, ConfigItem_change_type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ConfigItem_change_type>(
    ConfigItem_change_type_descriptor(), name, value);
}
enum Event_EventType {
  Event_EventType_HSET = 0,
  Event_EventType_SET = 1,
  Event_EventType_ADD = 2,
  Event_EventType_DEL = 3,
  Event_EventType_Event_EventType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Event_EventType_Event_EventType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Event_EventType_IsValid(int value);
const Event_EventType Event_EventType_EventType_MIN = Event_EventType_HSET;
const Event_EventType Event_EventType_EventType_MAX = Event_EventType_DEL;
const int Event_EventType_EventType_ARRAYSIZE = Event_EventType_EventType_MAX + 1;

const ::google::protobuf::EnumDescriptor* Event_EventType_descriptor();
inline const ::std::string& Event_EventType_Name(Event_EventType value) {
  return ::google::protobuf::internal::NameOfEnum(
    Event_EventType_descriptor(), value);
}
inline bool Event_EventType_Parse(
    const ::std::string& name, Event_EventType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Event_EventType>(
    Event_EventType_descriptor(), name, value);
}
// ===================================================================

class Empty : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ss7config.Empty) */ {
 public:
  Empty();
  virtual ~Empty();

  Empty(const Empty& from);

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(Empty&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Empty& default_instance();

  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Empty* other);
  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Empty* New() const PROTOBUF_FINAL { return New(NULL); }

  Empty* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Empty& from);
  void MergeFrom(const Empty& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Empty* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:ss7config.Empty)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend struct protobuf_kv_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class KVs : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ss7config.KVs) */ {
 public:
  KVs();
  virtual ~KVs();

  KVs(const KVs& from);

  inline KVs& operator=(const KVs& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  KVs(KVs&& from) noexcept
    : KVs() {
    *this = ::std::move(from);
  }

  inline KVs& operator=(KVs&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const KVs& default_instance();

  static inline const KVs* internal_default_instance() {
    return reinterpret_cast<const KVs*>(
               &_KVs_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(KVs* other);
  friend void swap(KVs& a, KVs& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline KVs* New() const PROTOBUF_FINAL { return New(NULL); }

  KVs* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const KVs& from);
  void MergeFrom(const KVs& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(KVs* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, string> kv = 1;
  int kv_size() const;
  void clear_kv();
  static const int kKvFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::std::string >&
      kv() const;
  ::google::protobuf::Map< ::std::string, ::std::string >*
      mutable_kv();

  // @@protoc_insertion_point(class_scope:ss7config.KVs)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class KVs_KvEntry : public ::google::protobuf::internal::MapEntry<KVs_KvEntry, 
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<KVs_KvEntry, 
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > SuperType;
    KVs_KvEntry();
    KVs_KvEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const KVs_KvEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_KVs_KvEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      KVs_KvEntry,
      ::std::string, ::std::string,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      0 > kv_;
  private:
  mutable int _cached_size_;
  friend struct protobuf_kv_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class ConfigItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ss7config.ConfigItem) */ {
 public:
  ConfigItem();
  virtual ~ConfigItem();

  ConfigItem(const ConfigItem& from);

  inline ConfigItem& operator=(const ConfigItem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConfigItem(ConfigItem&& from) noexcept
    : ConfigItem() {
    *this = ::std::move(from);
  }

  inline ConfigItem& operator=(ConfigItem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigItem& default_instance();

  static inline const ConfigItem* internal_default_instance() {
    return reinterpret_cast<const ConfigItem*>(
               &_ConfigItem_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(ConfigItem* other);
  friend void swap(ConfigItem& a, ConfigItem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConfigItem* New() const PROTOBUF_FINAL { return New(NULL); }

  ConfigItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConfigItem& from);
  void MergeFrom(const ConfigItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConfigItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  typedef ConfigItem_change_type change_type;
  static const change_type NEW =
    ConfigItem_change_type_NEW;
  static const change_type MODIFIED =
    ConfigItem_change_type_MODIFIED;
  static inline bool change_type_IsValid(int value) {
    return ConfigItem_change_type_IsValid(value);
  }
  static const change_type change_type_MIN =
    ConfigItem_change_type_change_type_MIN;
  static const change_type change_type_MAX =
    ConfigItem_change_type_change_type_MAX;
  static const int change_type_ARRAYSIZE =
    ConfigItem_change_type_change_type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  change_type_descriptor() {
    return ConfigItem_change_type_descriptor();
  }
  static inline const ::std::string& change_type_Name(change_type value) {
    return ConfigItem_change_type_Name(value);
  }
  static inline bool change_type_Parse(const ::std::string& name,
      change_type* value) {
    return ConfigItem_change_type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // map<string, .ss7config.KVs> children_fields = 3;
  int children_fields_size() const;
  void clear_children_fields();
  static const int kChildrenFieldsFieldNumber = 3;
  const ::google::protobuf::Map< ::std::string, ::ss7config::KVs >&
      children_fields() const;
  ::google::protobuf::Map< ::std::string, ::ss7config::KVs >*
      mutable_children_fields();

  // string key = 1;
  void clear_key();
  static const int kKeyFieldNumber = 1;
  const ::std::string& key() const;
  void set_key(const ::std::string& value);
  #if LANG_CXX11
  void set_key(::std::string&& value);
  #endif
  void set_key(const char* value);
  void set_key(const char* value, size_t size);
  ::std::string* mutable_key();
  ::std::string* release_key();
  void set_allocated_key(::std::string* key);

  // .ss7config.KVs parent_fields = 2;
  bool has_parent_fields() const;
  void clear_parent_fields();
  static const int kParentFieldsFieldNumber = 2;
  const ::ss7config::KVs& parent_fields() const;
  ::ss7config::KVs* mutable_parent_fields();
  ::ss7config::KVs* release_parent_fields();
  void set_allocated_parent_fields(::ss7config::KVs* parent_fields);

  // @@protoc_insertion_point(class_scope:ss7config.ConfigItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class ConfigItem_ChildrenFieldsEntry : public ::google::protobuf::internal::MapEntry<ConfigItem_ChildrenFieldsEntry, 
      ::std::string, ::ss7config::KVs,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<ConfigItem_ChildrenFieldsEntry, 
      ::std::string, ::ss7config::KVs,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > SuperType;
    ConfigItem_ChildrenFieldsEntry();
    ConfigItem_ChildrenFieldsEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const ConfigItem_ChildrenFieldsEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_ConfigItem_ChildrenFieldsEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      ConfigItem_ChildrenFieldsEntry,
      ::std::string, ::ss7config::KVs,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > children_fields_;
  private:
  ::google::protobuf::internal::ArenaStringPtr key_;
  ::ss7config::KVs* parent_fields_;
  mutable int _cached_size_;
  friend struct protobuf_kv_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class ConfigGroup : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ss7config.ConfigGroup) */ {
 public:
  ConfigGroup();
  virtual ~ConfigGroup();

  ConfigGroup(const ConfigGroup& from);

  inline ConfigGroup& operator=(const ConfigGroup& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConfigGroup(ConfigGroup&& from) noexcept
    : ConfigGroup() {
    *this = ::std::move(from);
  }

  inline ConfigGroup& operator=(ConfigGroup&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConfigGroup& default_instance();

  static inline const ConfigGroup* internal_default_instance() {
    return reinterpret_cast<const ConfigGroup*>(
               &_ConfigGroup_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(ConfigGroup* other);
  friend void swap(ConfigGroup& a, ConfigGroup& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConfigGroup* New() const PROTOBUF_FINAL { return New(NULL); }

  ConfigGroup* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConfigGroup& from);
  void MergeFrom(const ConfigGroup& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConfigGroup* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .ss7config.ConfigItem> config_items = 1;
  int config_items_size() const;
  void clear_config_items();
  static const int kConfigItemsFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::ss7config::ConfigItem >&
      config_items() const;
  ::google::protobuf::Map< ::std::string, ::ss7config::ConfigItem >*
      mutable_config_items();

  // @@protoc_insertion_point(class_scope:ss7config.ConfigGroup)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class ConfigGroup_ConfigItemsEntry : public ::google::protobuf::internal::MapEntry<ConfigGroup_ConfigItemsEntry, 
      ::std::string, ::ss7config::ConfigItem,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<ConfigGroup_ConfigItemsEntry, 
      ::std::string, ::ss7config::ConfigItem,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > SuperType;
    ConfigGroup_ConfigItemsEntry();
    ConfigGroup_ConfigItemsEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const ConfigGroup_ConfigItemsEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_ConfigGroup_ConfigItemsEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      ConfigGroup_ConfigItemsEntry,
      ::std::string, ::ss7config::ConfigItem,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > config_items_;
  private:
  mutable int _cached_size_;
  friend struct protobuf_kv_2eproto::TableStruct;
};
// -------------------------------------------------------------------


// -------------------------------------------------------------------

class ss7Config : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ss7config.ss7Config) */ {
 public:
  ss7Config();
  virtual ~ss7Config();

  ss7Config(const ss7Config& from);

  inline ss7Config& operator=(const ss7Config& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ss7Config(ss7Config&& from) noexcept
    : ss7Config() {
    *this = ::std::move(from);
  }

  inline ss7Config& operator=(ss7Config&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ss7Config& default_instance();

  static inline const ss7Config* internal_default_instance() {
    return reinterpret_cast<const ss7Config*>(
               &_ss7Config_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    8;

  void Swap(ss7Config* other);
  friend void swap(ss7Config& a, ss7Config& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ss7Config* New() const PROTOBUF_FINAL { return New(NULL); }

  ss7Config* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ss7Config& from);
  void MergeFrom(const ss7Config& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ss7Config* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  // map<string, .ss7config.ConfigGroup> ss7_config = 1;
  int ss7_config_size() const;
  void clear_ss7_config();
  static const int kSs7ConfigFieldNumber = 1;
  const ::google::protobuf::Map< ::std::string, ::ss7config::ConfigGroup >&
      ss7_config() const;
  ::google::protobuf::Map< ::std::string, ::ss7config::ConfigGroup >*
      mutable_ss7_config();

  // @@protoc_insertion_point(class_scope:ss7config.ss7Config)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  public:
  class ss7Config_Ss7ConfigEntry : public ::google::protobuf::internal::MapEntry<ss7Config_Ss7ConfigEntry, 
      ::std::string, ::ss7config::ConfigGroup,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > {
  public:
    typedef ::google::protobuf::internal::MapEntry<ss7Config_Ss7ConfigEntry, 
      ::std::string, ::ss7config::ConfigGroup,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > SuperType;
    ss7Config_Ss7ConfigEntry();
    ss7Config_Ss7ConfigEntry(::google::protobuf::Arena* arena);
    void MergeFrom(const ::google::protobuf::Message& other) PROTOBUF_FINAL;
    void MergeFrom(const ss7Config_Ss7ConfigEntry& other);
    static const Message* internal_default_instance() { return reinterpret_cast<const Message*>(&_ss7Config_Ss7ConfigEntry_default_instance_); }
    ::google::protobuf::Metadata GetMetadata() const;
  };
  private:
  ::google::protobuf::internal::MapField<
      ss7Config_Ss7ConfigEntry,
      ::std::string, ::ss7config::ConfigGroup,
      ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
      ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
      0 > ss7_config_;
  private:
  mutable int _cached_size_;
  friend struct protobuf_kv_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Event : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ss7config.Event) */ {
 public:
  Event();
  virtual ~Event();

  Event(const Event& from);

  inline Event& operator=(const Event& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Event(Event&& from) noexcept
    : Event() {
    *this = ::std::move(from);
  }

  inline Event& operator=(Event&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Event& default_instance();

  static inline const Event* internal_default_instance() {
    return reinterpret_cast<const Event*>(
               &_Event_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    9;

  void Swap(Event* other);
  friend void swap(Event& a, Event& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Event* New() const PROTOBUF_FINAL { return New(NULL); }

  Event* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Event& from);
  void MergeFrom(const Event& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Event* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef Event_EventType EventType;
  static const EventType HSET =
    Event_EventType_HSET;
  static const EventType SET =
    Event_EventType_SET;
  static const EventType ADD =
    Event_EventType_ADD;
  static const EventType DEL =
    Event_EventType_DEL;
  static inline bool EventType_IsValid(int value) {
    return Event_EventType_IsValid(value);
  }
  static const EventType EventType_MIN =
    Event_EventType_EventType_MIN;
  static const EventType EventType_MAX =
    Event_EventType_EventType_MAX;
  static const int EventType_ARRAYSIZE =
    Event_EventType_EventType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  EventType_descriptor() {
    return Event_EventType_descriptor();
  }
  static inline const ::std::string& EventType_Name(EventType value) {
    return Event_EventType_Name(value);
  }
  static inline bool EventType_Parse(const ::std::string& name,
      EventType* value) {
    return Event_EventType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // .ss7config.ConfigItem config_item = 2;
  bool has_config_item() const;
  void clear_config_item();
  static const int kConfigItemFieldNumber = 2;
  const ::ss7config::ConfigItem& config_item() const;
  ::ss7config::ConfigItem* mutable_config_item();
  ::ss7config::ConfigItem* release_config_item();
  void set_allocated_config_item(::ss7config::ConfigItem* config_item);

  // .ss7config.Event.EventType event_type = 1;
  void clear_event_type();
  static const int kEventTypeFieldNumber = 1;
  ::ss7config::Event_EventType event_type() const;
  void set_event_type(::ss7config::Event_EventType value);

  // @@protoc_insertion_point(class_scope:ss7config.Event)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::ss7config::ConfigItem* config_item_;
  int event_type_;
  mutable int _cached_size_;
  friend struct protobuf_kv_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Empty

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// KVs

// map<string, string> kv = 1;
inline int KVs::kv_size() const {
  return kv_.size();
}
inline void KVs::clear_kv() {
  kv_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::std::string >&
KVs::kv() const {
  // @@protoc_insertion_point(field_map:ss7config.KVs.kv)
  return kv_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::std::string >*
KVs::mutable_kv() {
  // @@protoc_insertion_point(field_mutable_map:ss7config.KVs.kv)
  return kv_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ConfigItem

// string key = 1;
inline void ConfigItem::clear_key() {
  key_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConfigItem::key() const {
  // @@protoc_insertion_point(field_get:ss7config.ConfigItem.key)
  return key_.GetNoArena();
}
inline void ConfigItem::set_key(const ::std::string& value) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ss7config.ConfigItem.key)
}
#if LANG_CXX11
inline void ConfigItem::set_key(::std::string&& value) {
  
  key_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ss7config.ConfigItem.key)
}
#endif
inline void ConfigItem::set_key(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ss7config.ConfigItem.key)
}
inline void ConfigItem::set_key(const char* value, size_t size) {
  
  key_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ss7config.ConfigItem.key)
}
inline ::std::string* ConfigItem::mutable_key() {
  
  // @@protoc_insertion_point(field_mutable:ss7config.ConfigItem.key)
  return key_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConfigItem::release_key() {
  // @@protoc_insertion_point(field_release:ss7config.ConfigItem.key)
  
  return key_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConfigItem::set_allocated_key(::std::string* key) {
  if (key != NULL) {
    
  } else {
    
  }
  key_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), key);
  // @@protoc_insertion_point(field_set_allocated:ss7config.ConfigItem.key)
}

// .ss7config.KVs parent_fields = 2;
inline bool ConfigItem::has_parent_fields() const {
  return this != internal_default_instance() && parent_fields_ != NULL;
}
inline void ConfigItem::clear_parent_fields() {
  if (GetArenaNoVirtual() == NULL && parent_fields_ != NULL) delete parent_fields_;
  parent_fields_ = NULL;
}
inline const ::ss7config::KVs& ConfigItem::parent_fields() const {
  const ::ss7config::KVs* p = parent_fields_;
  // @@protoc_insertion_point(field_get:ss7config.ConfigItem.parent_fields)
  return p != NULL ? *p : *reinterpret_cast<const ::ss7config::KVs*>(
      &::ss7config::_KVs_default_instance_);
}
inline ::ss7config::KVs* ConfigItem::mutable_parent_fields() {
  
  if (parent_fields_ == NULL) {
    parent_fields_ = new ::ss7config::KVs;
  }
  // @@protoc_insertion_point(field_mutable:ss7config.ConfigItem.parent_fields)
  return parent_fields_;
}
inline ::ss7config::KVs* ConfigItem::release_parent_fields() {
  // @@protoc_insertion_point(field_release:ss7config.ConfigItem.parent_fields)
  
  ::ss7config::KVs* temp = parent_fields_;
  parent_fields_ = NULL;
  return temp;
}
inline void ConfigItem::set_allocated_parent_fields(::ss7config::KVs* parent_fields) {
  delete parent_fields_;
  parent_fields_ = parent_fields;
  if (parent_fields) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ss7config.ConfigItem.parent_fields)
}

// map<string, .ss7config.KVs> children_fields = 3;
inline int ConfigItem::children_fields_size() const {
  return children_fields_.size();
}
inline void ConfigItem::clear_children_fields() {
  children_fields_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::ss7config::KVs >&
ConfigItem::children_fields() const {
  // @@protoc_insertion_point(field_map:ss7config.ConfigItem.children_fields)
  return children_fields_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::ss7config::KVs >*
ConfigItem::mutable_children_fields() {
  // @@protoc_insertion_point(field_mutable_map:ss7config.ConfigItem.children_fields)
  return children_fields_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ConfigGroup

// map<string, .ss7config.ConfigItem> config_items = 1;
inline int ConfigGroup::config_items_size() const {
  return config_items_.size();
}
inline void ConfigGroup::clear_config_items() {
  config_items_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::ss7config::ConfigItem >&
ConfigGroup::config_items() const {
  // @@protoc_insertion_point(field_map:ss7config.ConfigGroup.config_items)
  return config_items_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::ss7config::ConfigItem >*
ConfigGroup::mutable_config_items() {
  // @@protoc_insertion_point(field_mutable_map:ss7config.ConfigGroup.config_items)
  return config_items_.MutableMap();
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// ss7Config

// map<string, .ss7config.ConfigGroup> ss7_config = 1;
inline int ss7Config::ss7_config_size() const {
  return ss7_config_.size();
}
inline void ss7Config::clear_ss7_config() {
  ss7_config_.Clear();
}
inline const ::google::protobuf::Map< ::std::string, ::ss7config::ConfigGroup >&
ss7Config::ss7_config() const {
  // @@protoc_insertion_point(field_map:ss7config.ss7Config.ss7_config)
  return ss7_config_.GetMap();
}
inline ::google::protobuf::Map< ::std::string, ::ss7config::ConfigGroup >*
ss7Config::mutable_ss7_config() {
  // @@protoc_insertion_point(field_mutable_map:ss7config.ss7Config.ss7_config)
  return ss7_config_.MutableMap();
}

// -------------------------------------------------------------------

// Event

// .ss7config.Event.EventType event_type = 1;
inline void Event::clear_event_type() {
  event_type_ = 0;
}
inline ::ss7config::Event_EventType Event::event_type() const {
  // @@protoc_insertion_point(field_get:ss7config.Event.event_type)
  return static_cast< ::ss7config::Event_EventType >(event_type_);
}
inline void Event::set_event_type(::ss7config::Event_EventType value) {
  
  event_type_ = value;
  // @@protoc_insertion_point(field_set:ss7config.Event.event_type)
}

// .ss7config.ConfigItem config_item = 2;
inline bool Event::has_config_item() const {
  return this != internal_default_instance() && config_item_ != NULL;
}
inline void Event::clear_config_item() {
  if (GetArenaNoVirtual() == NULL && config_item_ != NULL) delete config_item_;
  config_item_ = NULL;
}
inline const ::ss7config::ConfigItem& Event::config_item() const {
  const ::ss7config::ConfigItem* p = config_item_;
  // @@protoc_insertion_point(field_get:ss7config.Event.config_item)
  return p != NULL ? *p : *reinterpret_cast<const ::ss7config::ConfigItem*>(
      &::ss7config::_ConfigItem_default_instance_);
}
inline ::ss7config::ConfigItem* Event::mutable_config_item() {
  
  if (config_item_ == NULL) {
    config_item_ = new ::ss7config::ConfigItem;
  }
  // @@protoc_insertion_point(field_mutable:ss7config.Event.config_item)
  return config_item_;
}
inline ::ss7config::ConfigItem* Event::release_config_item() {
  // @@protoc_insertion_point(field_release:ss7config.Event.config_item)
  
  ::ss7config::ConfigItem* temp = config_item_;
  config_item_ = NULL;
  return temp;
}
inline void Event::set_allocated_config_item(::ss7config::ConfigItem* config_item) {
  delete config_item_;
  config_item_ = config_item;
  if (config_item) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:ss7config.Event.config_item)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace ss7config

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ss7config::ConfigItem_change_type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ss7config::ConfigItem_change_type>() {
  return ::ss7config::ConfigItem_change_type_descriptor();
}
template <> struct is_proto_enum< ::ss7config::Event_EventType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ss7config::Event_EventType>() {
  return ::ss7config::Event_EventType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_kv_2eproto__INCLUDED
