// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sessiond.proto
#ifndef GRPC_sessiond_2eproto__INCLUDED
#define GRPC_sessiond_2eproto__INCLUDED

#include "sessiond.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace sessiond {

// The greeting service definition.
class Watch final {
 public:
  static constexpr char const* service_full_name() {
    return "sessiond.Watch";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sessiond::sessionRequest, ::sessiond::sessionResponse>> watchKill(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::sessiond::sessionRequest, ::sessiond::sessionResponse>>(watchKillRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sessiond::sessionRequest, ::sessiond::sessionResponse>> AsyncwatchKill(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::sessiond::sessionRequest, ::sessiond::sessionResponse>>(AsyncwatchKillRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::sessiond::sessionRequest, ::sessiond::sessionResponse>* watchKillRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::sessiond::sessionRequest, ::sessiond::sessionResponse>* AsyncwatchKillRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::sessiond::sessionRequest, ::sessiond::sessionResponse>> watchKill(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::sessiond::sessionRequest, ::sessiond::sessionResponse>>(watchKillRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::sessiond::sessionRequest, ::sessiond::sessionResponse>> AsyncwatchKill(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::sessiond::sessionRequest, ::sessiond::sessionResponse>>(AsyncwatchKillRaw(context, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::sessiond::sessionRequest, ::sessiond::sessionResponse>* watchKillRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::sessiond::sessionRequest, ::sessiond::sessionResponse>* AsyncwatchKillRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    const ::grpc::RpcMethod rpcmethod_watchKill_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status watchKill(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sessiond::sessionResponse, ::sessiond::sessionRequest>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_watchKill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_watchKill() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_watchKill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status watchKill(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sessiond::sessionResponse, ::sessiond::sessionRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestwatchKill(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::sessiond::sessionResponse, ::sessiond::sessionRequest>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_watchKill<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_watchKill : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_watchKill() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_watchKill() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status watchKill(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::sessiond::sessionResponse, ::sessiond::sessionRequest>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace sessiond


#endif  // GRPC_sessiond_2eproto__INCLUDED
